version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/lastseenping
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=G5+1mMbYwjhH9t6P7Zx9eHj+qdcMoyex8O+L03t7ow4=
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=lastseenping
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
