apiVersion: apps/v1
kind: Deployment
metadata:
  name: last-seen-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: last-seen-web
  template:
    metadata:
      labels:
        app: last-seen-web
    spec:
      containers:
      - name: last-seen-web
        image: last-seen-web:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/last_seen"
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NEXTAUTH_URL
          value: "http://$(NODE_IP):31000"
        - name: NEXTAUTH_SECRET
          value: "G5+1mMbYwjhH9t6P7Zx9eHj+qdcMoyex8O+L03t7ow4="
