apiVersion: v1
kind: Service
metadata:
  name: last-seen-web-service
spec:
  selector:
    app: last-seen-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 31000
  type: LoadBalancer
