apiVersion: apps/v1
kind: Deployment
metadata:
  name: last-seen-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: last-seen-web
  template:
    metadata:
      labels:
        app: last-seen-web
    spec:
      containers:
      - name: last-seen-web
        image: last-seen-web:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/last_seen"
